# docker-compose.yml

version: '3.8'

services:
  # フロントエンドサービス
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000/api
    depends_on:
      - backend
    networks:
      - app_network
    command: npm run dev

  # バックエンドサービス
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backups:/app/backups
    environment:
      - ENVIRONMENT=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=startup_wellness_analyze
      - DB_USER=postgres
      - DB_PASSWORD=1spel!2stack3win
      - DATABASE_URL=postgresql://postgres:1spel!2stack3win@db:5432/startup_wellness_analyze
      - PYTHONPATH=/app/src:/app
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRICE_ID_BASIC=${STRIPE_PRICE_ID_BASIC}
      - STRIPE_PRICE_ID_PRO=${STRIPE_PRICE_ID_PRO}
      - STRIPE_PRICE_ID_ENTERPRISE=${STRIPE_PRICE_ID_ENTERPRISE}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    command: bash -c "cd /app && python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  # データベースサービス
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=startup_wellness_analyze
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1spel!2stack3win
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

# 永続化用のボリューム定義
volumes:
  postgres_data:
    name: wellness_postgres_data
  frontend_node_modules:
    name: wellness_frontend_node_modules
  frontend_dist:
    name: wellness_frontend_dist

# ネットワーク定義
networks:
  app_network:
    driver: bridge