# Cloud Buildパイプライン設定
steps:
  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/startup-wellness-backend', '.']

  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/startup-wellness-backend']

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'startup-wellness-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/startup-wellness-backend'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'

# イメージをContainer Registryに保存
images:
  - 'gcr.io/$PROJECT_ID/startup-wellness-backend'

# タイムアウト設定（デフォルト: 10分）
timeout: '1200s'